version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: { }

services:
  transaction-app-container:
    image: account-app-service:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/account-app-service
    ports:
      - "8081:8081"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

